name : Hello CI

on : push
  
jobs:
  hello :
    runs-on : ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: List files (before checkout)
        run: ls -la

      - name: Get the repo code
        uses: actions/checkout@v4

      - name: List files (after checkout)
        run: ls -la
